export enum AuditAction {
  // Platform Admin & Root Actions
  BOOTSTRAP_ROOT = 'BOOTSTRAP_ROOT',
  CREATE_PLATFORM_ADMIN = 'CREATE_PLATFORM_ADMIN',
  UPDATE_PLATFORM_ADMIN = 'UPDATE_PLATFORM_ADMIN',
  SUSPEND_PLATFORM_ADMIN = 'SUSPEND_PLATFORM_ADMIN',
  ACTIVATE_PLATFORM_ADMIN = 'ACTIVATE_PLATFORM_ADMIN',
  DELETE_PLATFORM_ADMIN = 'DELETE_PLATFORM_ADMIN',
  RESET_PLATFORM_ADMIN_PASSWORD = 'RESET_PLATFORM_ADMIN_PASSWORD',

  // Tenant Management
  CREATE_TENANT = 'CREATE_TENANT',
  UPDATE_TENANT = 'UPDATE_TENANT',
  UPDATE_TENANT_STATUS = 'UPDATE_TENANT_STATUS',
  DELETE_TENANT = 'DELETE_TENANT',
  ASSIGN_PLAN = 'ASSIGN_PLAN',

  // Tenant User Management (by Platform Staff)
  RESET_TENANT_USER_PASSWORD = 'RESET_TENANT_USER_PASSWORD',

  // Subscription Plan Management
  CREATE_PLAN = 'CREATE_PLAN',
  UPDATE_PLAN = 'UPDATE_PLAN',
  DELETE_PLAN = 'DELETE_PLAN',

  // Auth Actions (Optional, but useful)
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',

  // Support Actions
  CREATE_TICKET = 'CREATE_TICKET',
  UPDATE_TICKET_STATUS = 'UPDATE_TICKET_STATUS',
  REPLY_TICKET = 'REPLY_TICKET',
  ASSIGN_TICKET = 'ASSIGN_TICKET',
}
