export enum TenantRole {
  TENANT_ADMIN = 'TENANT_ADMIN',
  BUSINESS_MANAGER = 'BUSINESS_MANAGER',
  SALES_STAFF = 'SALES_STAFF',
  INVENTORY_MANAGER = 'INVENTORY_MANAGER',
  FINANCE_MANAGER = 'FINANCE_MANAGER',
  VIEWER = 'VIEWER',
}
